name: Old Linux Support

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.70.0
        libraries: container headers system thread
        platform: x64
        configuration: Release
        static: 1
        static-runtime: 1
    - name: make lib
      run: make -f Makefile_Linux BOOST_ROOT_PATH=${{steps.boost.outputs.root}} BOOST_LIB_PATH=${{steps.boost.outputs.librarydir}}
      working-directory: ai_src
    - name: make
      run: make -f Makefile_Linux BOOST_ROOT_PATH=${{steps.boost.outputs.root}} BOOST_LIB_PATH=${{steps.boost.outputs.librarydir}}
    - uses: actions/upload-artifact@v3
      with:
        name: linux-old
        path: |
          libai.so
          system.exe
